-- Q1. Display the first 20 rows from the customer table to check sample data
SELECT * FROM customer LIMIT 20;

-- Q2. What is the total revenue generated by male vs. female customers?
SELECT "Gender", SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender";



-- Q3. Which customers used a discount but still spent more than the average purchase amount?
SELECT "Customer ID", "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes'
  AND "Purchase Amount (USD)" >= (
      SELECT AVG("Purchase Amount (USD)")
      FROM customer
      WHERE "Purchase Amount (USD)" IS NOT NULL
  );

-- Q4. Which are the top 5 products with the highest average review rating?
SELECT 
    "Item Purchased", 
    ROUND(AVG("Review Rating")::numeric, 2) AS average_product_rating
FROM customer
GROUP BY "Item Purchased"
ORDER BY average_product_rating DESC
LIMIT 5;
-- Q5. Compare the average purchase amounts between Standard and Express Shipping.
SELECT "Shipping Type", ROUND(AVG("Purchase Amount (USD)")::numeric, 2) AS avg_purchase
FROM customer
WHERE "Shipping Type" IN ('Standard','Express')
GROUP BY "Shipping Type";

-- Q6. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT "Subscription Status",
       COUNT("Customer ID") AS total_customers,
       ROUND(AVG("Purchase Amount (USD)")::numeric,2) AS avg_spend,
       ROUND(SUM("Purchase Amount (USD)")::numeric,2) AS total_revenue
FROM customer
GROUP BY "Subscription Status"
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q7. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT "Item Purchased",
       ROUND(100.0 * SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END)/COUNT(*)::numeric, 2) AS discount_rate
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_rate DESC
LIMIT 5;

-- Q8. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
  SELECT "Customer ID", "Previous Purchases",
         CASE 
            WHEN "Previous Purchases" = 1 THEN 'New'
            WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
         END AS customer_segment
  FROM customer
)
SELECT customer_segment, COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

-- Q9. What are the top 3 most purchased products within each category?
WITH item_counts AS (
  SELECT "Category",
         "Item Purchased",
         COUNT("Customer ID") AS total_orders,
         ROW_NUMBER() OVER (PARTITION BY "Category" ORDER BY COUNT("Customer ID") DESC) AS item_rank
  FROM customer
  GROUP BY "Category", "Item Purchased"
)
SELECT item_rank, "Category", "Item Purchased", total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q10. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT "Subscription Status", COUNT("Customer ID") AS repeat_buyers
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";
-- Q11. What is the revenue contribution of each age group?
SELECT "Age" AS age_group, 
       SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Age"
ORDER BY total_revenue DESC;